apiVersion: v2
name: gitpod-monitoring
description: Monitoring for a Gitpod deployment
type: application
version: 0.0.0
icon: https://www.gitpod.io/svg/media-kit/logo-mark.svg
home: https://github.com/MrSimonEmms/gitpod-monitoring
dependencies:
  - name: kube-prometheus-stack
    alias: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: ^35.5.0
    condition: prometheus.enabled
maintainers:
  - name: Simon Emms
    email: simon@simonemms.com
    url: https://simonemms.com
keywords:
  - gitpod
  - monitoring
  - prometheus
  - grafana
